### ISSUE TITLE
Tracking cells encoding across sessions

### ISSUE THREAD

**Issue by alexpiet** [AllenInstitute/visual_behavior_glm#120]
- [ ] For each session get vector of dropout coefficients
- [ ] Across sessions, track angle, or distance between feature vectors
- [ ] can we pull out the VIP omission result?
- [ ] Do we see consistent cells, or variable cells?
- [ ] effects of active/passive
- [ ] effects of familiar/novel
