### ISSUE TITLE
TODO - Finalization for Platform paper

### ISSUE THREAD

**Issue by alexpiet** [AllenInstitute/visual_behavior_glm#276]
I'm using this issue as a landing page for finishing the GLM for the platform paper. 

**Executive decisions!**
- [x] Removing the `time` regressor
- [x] Removing the behavioral strategy model regressors
- [x] Removing `false-alarm` and `correct-reject` regressors
- [x] Removing `face-motion-energy` regressors. I don't trust the extracted PCs, Peter doesn't seem to have them on high priority, and they haven't shown to be a big influence on neural activity. 
- [x] Not including the DNN lick model.
- [x] Not including any population activity kernels. We just don't have time to significantly expand the scope of the project. 
- [x] When comparing kernels, don't include any normalization
- [x] [Set up a project board for the platform paper version of the model ](https://github.com/AllenInstitute/visual_behavior_glm/projects/7)
- [x] Only looking at valid ROIs. Doug had been looking at invalid ROIs to try to unfail some ROIs, but I'm going to mothball that effort

**Data Decisions**
- [x] Fitting to df/f or events? 
   - I'm going to fit both df/f and events, but focus my analysis on events
- [x] No, but this will get handled in VBA
- [x] Do we have a fixed definition for picking between multiple F or N > 1 sessions?
   - [x] I'm going to fit all sessions, then we can filter in analysis steps

**Things to do with how the model works**
- [x] Clean up old github issues
- [x] be consistent about cell inclusion, overall variance explained threshold, feature specific variance explained
   - [x] Overall variance explained must be > 0.005
   - [x] No threshold for dropout scores 
- [x] how to normalize dropout scores across sessions. Maybe use the highest variance explained across sessions? 
   - [x] No normalization across sessions. 
- [x] make a function that confirms we are fitting all cells in the dataset
- [ ] regularization: L1, smoothing penalty (kernels smooth), Reduced Rank Regularization. 
- [x] Compute "explainable" variance, N. Steinmetz mentioned something, #257

**Analysis**
- [ ] Analyze engaged/disengaged model
- [ ] When combining mesoscope and scientifica, merge onto mesoscope timestamps
- [ ] fit model with omission broken into post-omission and within-omission (have first attempt)
- [ ] fit model with same regressors across all active/passive sessions (have first attempt)
- [ ] hit/miss image specific. (1) check for residual, see how often this happens, (2) try fitting the model
- [ ] running modulation of image response. (1) check for residual, see how often model fails to capture modulation by running. (2) Check for evidence of binary running states and running modulation. (3) try fitting model where we classify each image as a low-running epoch, or high-running epoch, and have two separate kernels for each image. 
- [ ] Stable vs. Unstable cells
- [ ] Ask where we see significant differences in dropout scores across sessions and cre-lines. Just enumerate where there are differences, making standard criteria for this determination. 
- [ ] Alex has seen some excitatory cells are omission responsive. 
- [ ] clustering on kernel shapes
